import type { DisclosureMode } from "../config/config.js";

const DISCLOSURE_HEADER = "X-Simulated-Response";
const DISCLOSURE_VALUE = "ip-vulture; simulated-response";
const DISCLOSURE_COMMENT =
  "<!-- This is a simulated HTTP response generated by ip-vulture. It does not represent a real server or a real system. -->";

interface DisclosedResponse {
  readonly body: string;
  readonly headers: Readonly<Record<string, string>>;
}

function isHtml(contentType: string | undefined): boolean {
  return contentType?.toLowerCase().includes("html") ?? false;
}

function applyDisclosure(
  mode: DisclosureMode,
  body: string,
  contentType: string | undefined,
  headers: Readonly<Record<string, string>>,
): DisclosedResponse {
  const wantsHeader = mode === "header" || mode === "both";
  const wantsComment = mode === "comment" || mode === "both";

  const disclosedHeaders = wantsHeader
    ? { ...headers, [DISCLOSURE_HEADER]: DISCLOSURE_VALUE }
    : headers;

  const disclosedBody =
    wantsComment && isHtml(contentType) && body.length > 0
      ? `${body}${DISCLOSURE_COMMENT}\n`
      : body;

  return Object.freeze({
    body: disclosedBody,
    headers: Object.freeze(disclosedHeaders),
  });
}

export {
  applyDisclosure,
  DISCLOSURE_COMMENT,
  DISCLOSURE_HEADER,
  DISCLOSURE_VALUE,
  type DisclosedResponse,
};
